//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContenedorXOrdenTransporte
    {
        public int IDOrdenTransporte { get; set; }
        public int IDContenedor { get; set; }
    
        public virtual Contenedor Contenedor { get; set; }
        public virtual OrdenTransporte OrdenTransporte { get; set; }
        public virtual ContenedorXOrdenTransporte ContenedorXOrdenTransporte1 { get; set; }
        public virtual ContenedorXOrdenTransporte ContenedorXOrdenTransporte2 { get; set; }
    }
}
