//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContenedorXOrdenTransporte
    {
        public int IDOrdenTransporte { get; set; }
        public int IDContenedor { get; set; }
    
        public virtual Contenedor Contenedor { get; set; }
        public virtual OrdenTransporte OrdenTransporte { get; set; }
        public virtual ContenedorXOrdenTransporte ContenedorXOrdenTransporte1 { get; set; }
        public virtual ContenedorXOrdenTransporte ContenedorXOrdenTransporte2 { get; set; }
    }
}
