//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contenedor
    {
        public Contenedor()
        {
            this.ContenedorXOrdenTransporte = new HashSet<ContenedorXOrdenTransporte>();
        }
    
        public int IDContenedor { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public string Observacion { get; set; }
        public string EstadoContenedor { get; set; }
        public int IDFichaTratamiento { get; set; }
    
        public virtual ICollection<ContenedorXOrdenTransporte> ContenedorXOrdenTransporte { get; set; }
        public virtual FichaTratamiento FichaTratamiento { get; set; }
    }
}
