//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleHistoriaClinica
    {
        public int IDDetalleHistoriaClinica { get; set; }
        public System.DateTime FechaConsulta { get; set; }
        public string Motivo { get; set; }
        public int IDHistoriaClinica { get; set; }
    
        public virtual HistoriaClinica HistoriaClinica { get; set; }
    }
}
