//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleHistoriaClinica
    {
        public int IDDetalleHistoriaClinica { get; set; }
        public System.DateTime FechaConsulta { get; set; }
        public string Motivo { get; set; }
        public int IDHistoriaClinica { get; set; }
    
        public virtual HistoriaClinica HistoriaClinica { get; set; }
    }
}
