//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFichaTratamiento
    {
        public int IDDetalleFichaTratamiento { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaSesion { get; set; }
        public int NroSesion { get; set; }
        public string EstadoPaciente { get; set; }
        public int IDFichaTratamiento { get; set; }
        public int IDGuiaContingencia { get; set; }
        public int IDProtocolo { get; set; }
        public Nullable<int> IDHojaPreparacion { get; set; }
    
        public virtual FichaTratamiento FichaTratamiento { get; set; }
        public virtual GuiaContingencia GuiaContingencia { get; set; }
        public virtual HojaPreparacion HojaPreparacion { get; set; }
        public virtual Protocolo Protocolo { get; set; }
    }
}
