//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.FichaTratamiento = new HashSet<FichaTratamiento>();
            this.HojaPreparacion = new HashSet<HojaPreparacion>();
        }
    
        public int IDEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int Turno { get; set; }
        public int TipoEmpleado { get; set; }
    
        public virtual ICollection<FichaTratamiento> FichaTratamiento { get; set; }
        public virtual ICollection<HojaPreparacion> HojaPreparacion { get; set; }
    }
}
