//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaTransporte
    {
        public EmpresaTransporte()
        {
            this.OrdenTransporte = new HashSet<OrdenTransporte>();
        }
    
        public int IDEmpresa { get; set; }
        public string Nombre { get; set; }
        public int Telefono { get; set; }
        public int RUC { get; set; }
        public int NroObservaciones { get; set; }
        public System.DateTime FechaInicioActividades { get; set; }
        public double CostoViaje { get; set; }
    
        public virtual ICollection<OrdenTransporte> OrdenTransporte { get; set; }
    }
}
