//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaTransporte
    {
        public EmpresaTransporte()
        {
            this.OrdenTransporte = new HashSet<OrdenTransporte>();
        }
    
        public int IDEmpresa { get; set; }
        public string Nombre { get; set; }
        public int Telefono { get; set; }
        public int RUC { get; set; }
        public int NroObservaciones { get; set; }
        public System.DateTime FechaInicioActividades { get; set; }
        public double CostoViaje { get; set; }
    
        public virtual ICollection<OrdenTransporte> OrdenTransporte { get; set; }
    }
}
