//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaTratamiento
    {
        public FichaTratamiento()
        {
            this.Contenedor = new HashSet<Contenedor>();
            this.DetalleFichaTratamiento = new HashSet<DetalleFichaTratamiento>();
        }
    
        public int IDFichaTratamiento { get; set; }
        public string EstadoFicha { get; set; }
        public int NroSesiones { get; set; }
        public int IntervaloSesion { get; set; }
        public string Diagnostico { get; set; }
        public string PlanAlimentacion { get; set; }
        public string EscalaActividad { get; set; }
        public int IDDetalleHistoriaClinica { get; set; }
        public int IDEmpleado { get; set; }
    
        public virtual ICollection<Contenedor> Contenedor { get; set; }
        public virtual ICollection<DetalleFichaTratamiento> DetalleFichaTratamiento { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual HistoriaClinica HistoriaClinica { get; set; }
    }
}
