//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiaContingencia
    {
        public GuiaContingencia()
        {
            this.DetalleFichaTratamiento = new HashSet<DetalleFichaTratamiento>();
        }
    
        public int IDGuiaContingencia { get; set; }
        public int TipoGuia { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<DetalleFichaTratamiento> DetalleFichaTratamiento { get; set; }
    }
}
