//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HojaPreparacion
    {
        public HojaPreparacion()
        {
            this.DetalleFichaTratamiento = new HashSet<DetalleFichaTratamiento>();
            this.Empleado = new HashSet<Empleado>();
        }
    
        public int IDHojaPreparacion { get; set; }
        public System.DateTime FechaPreparacion { get; set; }
        public string EstadoHoja { get; set; }
        public int CantidadResiduos { get; set; }
        public int IDProtocolo { get; set; }
    
        public virtual ICollection<DetalleFichaTratamiento> DetalleFichaTratamiento { get; set; }
        public virtual Protocolo Protocolo { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
    }
}
