//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialxPreparado
    {
        public int IDMaterial { get; set; }
        public int IDPreparado { get; set; }
        public double Dosis { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Preparado Preparado { get; set; }
    }
}
