//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialxPreparado
    {
        public int IDMaterial { get; set; }
        public int IDPreparado { get; set; }
        public int Dosis { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Preparado Preparado { get; set; }
    }
}
