//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OncologiaEntities : DbContext
    {
        public OncologiaEntities()
            : base("name=OncologiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contenedor> Contenedor { get; set; }
        public DbSet<ContenedorXOrdenTransporte> ContenedorXOrdenTransporte { get; set; }
        public DbSet<DetalleFichaTratamiento> DetalleFichaTratamiento { get; set; }
        public DbSet<DetalleHistoriaClinica> DetalleHistoriaClinica { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<EmpresaTransporte> EmpresaTransporte { get; set; }
        public DbSet<FichaTratamiento> FichaTratamiento { get; set; }
        public DbSet<GuiaContingencia> GuiaContingencia { get; set; }
        public DbSet<HistoriaClinica> HistoriaClinica { get; set; }
        public DbSet<HojaPreparacion> HojaPreparacion { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<MaterialxPreparado> MaterialxPreparado { get; set; }
        public DbSet<OrdenTransporte> OrdenTransporte { get; set; }
        public DbSet<Paciente> Paciente { get; set; }
        public DbSet<Preparado> Preparado { get; set; }
        public DbSet<Protocolo> Protocolo { get; set; }
        public DbSet<ProtocoloxPreparado> ProtocoloxPreparado { get; set; }
    }
}
