//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTransporte
    {
        public OrdenTransporte()
        {
            this.ContenedorXOrdenTransporte = new HashSet<ContenedorXOrdenTransporte>();
        }
    
        public int IDOrdenTransporte { get; set; }
        public System.DateTime FechaTransporte { get; set; }
        public int NumeroContenedores { get; set; }
        public string Comentario { get; set; }
        public int IDEmpresa { get; set; }
    
        public virtual ICollection<ContenedorXOrdenTransporte> ContenedorXOrdenTransporte { get; set; }
        public virtual EmpresaTransporte EmpresaTransporte { get; set; }
    }
}
