//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTransporte
    {
        public OrdenTransporte()
        {
            this.ContenedorXOrdenTransporte = new HashSet<ContenedorXOrdenTransporte>();
        }
    
        public int IDOrdenTransporte { get; set; }
        public System.DateTime FechaTransporte { get; set; }
        public int NumeroContenedores { get; set; }
        public string Comentario { get; set; }
        public int IDEmpresa { get; set; }
        public string NombreEmpresa { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<ContenedorXOrdenTransporte> ContenedorXOrdenTransporte { get; set; }
        public virtual EmpresaTransporte EmpresaTransporte { get; set; }
    }
}
