//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.HistoriaClinica = new HashSet<HistoriaClinica>();
        }
    
        public int IDPaciente { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public int DNI { get; set; }
        public int Edad { get; set; }
        public int Sexo { get; set; }
        public double Peso { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<HistoriaClinica> HistoriaClinica { get; set; }
    }
}
