//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.HistoriaClinica = new HashSet<HistoriaClinica>();
        }
    
        public int IDPaciente { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public int DNI { get; set; }
        public int Edad { get; set; }
        public int Sexo { get; set; }
        public double Peso { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<HistoriaClinica> HistoriaClinica { get; set; }
    }
}
