//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocoloxPreparado
    {
        public int IDProtocolo { get; set; }
        public int IDPreparado { get; set; }
    
        public virtual Preparado Preparado { get; set; }
        public virtual Protocolo Protocolo { get; set; }
        public virtual ProtocoloxPreparado ProtocoloxPreparado1 { get; set; }
        public virtual ProtocoloxPreparado ProtocoloxPreparado2 { get; set; }
    }
}
