//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protocolo
    {
        public Protocolo()
        {
            this.DetalleFichaTratamiento = new HashSet<DetalleFichaTratamiento>();
            this.HojaPreparacion = new HashSet<HojaPreparacion>();
            this.ProtocoloxPreparado = new HashSet<ProtocoloxPreparado>();
        }
    
        public int IDProtocolo { get; set; }
        public string NombreProtocolo { get; set; }
    
        public virtual ICollection<DetalleFichaTratamiento> DetalleFichaTratamiento { get; set; }
        public virtual ICollection<HojaPreparacion> HojaPreparacion { get; set; }
        public virtual ICollection<ProtocoloxPreparado> ProtocoloxPreparado { get; set; }
    }
}
