//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protocolo
    {
        public Protocolo()
        {
            this.DetalleFichaTratamiento = new HashSet<DetalleFichaTratamiento>();
            this.HojaPreparacion = new HashSet<HojaPreparacion>();
            this.ProtocoloxPreparado = new HashSet<ProtocoloxPreparado>();
        }
    
        public int IDProtocolo { get; set; }
        public string NombreProtocolo { get; set; }
    
        public virtual ICollection<DetalleFichaTratamiento> DetalleFichaTratamiento { get; set; }
        public virtual ICollection<HojaPreparacion> HojaPreparacion { get; set; }
        public virtual ICollection<ProtocoloxPreparado> ProtocoloxPreparado { get; set; }
    }
}
